---
- import_tasks: zabbix_proxy_iptables.yml
  when: iptables == 'true'
  tags: iptables
- import_tasks: zabbix_proxy_install.yml
  when: local != 'true'
  tags: install
- import_tasks: zabbix_proxy_local_install.yml
  when: local == 'true'
  tags: install
- import_tasks: zabbix_proxy_db.yml
  tags: config-db
- import_tasks: zabbix_proxy_config.yml
  tags: config
