#Iptables Config
iptables_accept_port: 10050
zabbix_agent_network: 10.10.11.0/24

# Install Config
#
iptables: false
local: true
rpm_delete: true
#deploy_env: ironic

# Main Config
zabbix_server_ip: 10.10.11.102
ListenPort: 10050
LogFile: /var/log/zabbix/zabbix_agentd.log
# zabbix ipatables agent network
# zabbix agent HostMetadata,different cluster,different value!
hostmetadata: cluster-one
AllowRoot: 1
deploy_env: ironic
